# Example of a seperate config file for prod
spring:
    config:
        activate:
            on-profile: prod
    data:
        mongodb:
            host: localhost
            port: 27017
            database: local